name: ci test
on: 
    push:
        branches: 
          - main
          - dev
          - ci-start

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          cd ./frontend
          npm install

        #   cd back-end
        #   npm install
    #   - name: Run back-end
    #     run:
    #       cd back-end
    #       npm run dev &
    #       sleep 10
    #       pkill -f "npm run dev"

      - name: Run front-end
        run: |
          cd ./frontend
          npm run dev &
          sleep 10
          pkill -f "npm run dev"
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: clone repo                          #conferir se precisa mesmo fazer o setup novamente pra testar ou se da pra dar run test direto
  #       uses: actions/setup-node@v3

  #     - name: setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18.x