name: CI Workflow
on: 
    push:
        branches: 
          - main
          - dev
          - ci-start

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          cd ./frontend
          npm install
        #   cd back-end
        #   npm install

    #   - name: Run back-end
    #     run:
    #       cd back-end
    #       npm run dev &
    #       sleep 10
    #       pkill -f "npm run dev"

      - name: Run front-end
        run: |
          cd ./frontend
          npm run dev &
          sleep 10
          pkill -f "npm run dev"
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          cd ./frontend
          npm install

      - name: run tests
        run: |
          cd ./frontend
          npx jest